
# Run tests in Node.js 0.10 and 0.12
language: node_js
node_js:
  - "0.10"
  - "0.12"

# Build only master and shunter-npm (plus pull-requests)
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Environment variables for the build
env:
  matrix:
    - "LINT=true"
    - "TEST=true"

# Build script
script:
  - 'if [ $LINT ]; then make lint; fi'
  - 'if [ $TEST ]; then make lcov-levels; fi'
